

[build]
  publish = "build1"
  command = "# no build command needed"
  
[dev]
  # Change if you use a different start command
  port = 8888  # Default Netlify Dev port
  targetPort = 3000  # Change if your app runs on a different port

